[Common] Header 구현
MOONSHOT-Team/MOONSHOT-CLIENT pull request #68
Opened 2024-01-09 14:07 UTC by Jun-min2

## 🔥 Related Issues

- close #22 

## 💜 작업 내용

- [x] Header UI
- [x] 페이지 link 연결

## ✅ PR Point
1. 피그마 수치에서 좌우가 1px 차이에 대해서 따로 신경쓰지 않고, 중간에 있으면 된다라는 생각으로 padding 값 최소화함 
2. 위와 같은 취지로( 기획자의 의도 파악..?) Header의 로고와 Navigation의 사이즈 3:2정도로 잡고 넣었음 

→ padding or margin으로 딱 맞추는게 좋으면 수정하겠습니다.

## 😡 Trouble Shooting
NavLink를 사용해서 페이지를 넘길 때 속성 값을 주는 방법에 대해 알아보았다. 
activeStyle, activeClassName은 없어졌고 className과 style만이 남았는데 두 방법의 속성 값 넣는 방법이 다름 주의! 

map함수를 이용할 때 매개변수를 지정하고, 해당 값을 내려주는 것에 많은 시간투자를 함..
## ☀️ 스크린샷 / GIF / 화면 녹화

## 📚 Reference

- 구현에 참고한 링크 (필요한 경우만 작성하고 없으면 지우기)
https://reactrouter.com/en/main/components/nav-link

2024-01-09 16:49 UTC, SooY2 approved these changes
**기획자의 의도가 뭔지 한번 물어보고** 양옆여백을 %,max-width, min-width로 조절하는 방법도 고려해보면 좋을거같습니당!! 짱준민 수고했다~~

2024-01-09 16:49 UTC, SooY2 commented on src/common/components/layout/Header/index.tsx
> +        {NAVIGATIONS.map(({ id, text, path }) => (
```
 {NAVIGATIONS.map(({ text, path }, idx) => (
    <StNavigation key={idx}>
```
id 지정해주는 대신 이렇게 map함수에서 인덱스 값 받아서 key값 지정해줄 수도 있습니다!! 참고참고~

2024-01-09 16:49 UTC, SooY2 commented on src/common/components/layout/Header/index.tsx
> +  width: 150%;
150%로 해준 이유가 몬가요??

2024-01-09 16:49 UTC, SooY2 commented on src/common/components/layout/Header/index.tsx
> +  width: 150%;
rem으로 하는거 추천합니다 !!

2024-01-09 16:49 UTC, SooY2 commented on src/common/components/layout/Header/index.tsx
> +  justify-content: space-between;
이미 StHeader에서 space-between으로 지정을 해줬기 때문에 따로 너비 지정해주지 않고 padding으로 조절해주면 될거같아요!

2024-01-10 00:10 UTC, Yeonseo-Jo requested changes
<img width="912" alt="image" src="https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/77691829/1112f05f-3146-46b9-865a-0674c3dc4f97">
<img width="529" alt="image" src="https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/77691829/42a6e893-6344-4491-b83e-618fb64a235b">

가운데 정렬이 안맞아요 ~
 그리고 `대쉬보드`는 뭘까요? 크흠.. 피그마 디자인 보고 만들어야 합니다 !!!!!!!
피그마 보고 마진 값 조정하기!

수정 후 리뷰 요청 다시 걸어주세요 -!

2024-01-10 00:10 UTC, Yeonseo-Jo commented on src/common/components/layout/Header/index.tsx
> +        {NAVIGATIONS.map(({ id, text, path }) => (
맞아요 다만 idx는 key 값으로 사용을 지양하는게 좋다고 합니다! 관련 내용도 같이 찾아보세용

2024-01-10 00:10 UTC, Yeonseo-Jo commented on src/common/components/layout/Header/index.tsx
> +                return { color: isActive ? 'white' : '' };
style은 사용하지 맙시다
styled-components나 css prop으로 바꿔주세요

2024-01-10 00:10 UTC, Yeonseo-Jo commented on src/common/constants/NavigationLink.ts
> +];
굿 좋습니당

2024-01-10 00:11 UTC, Yeonseo-Jo commented
<img width="352" alt="image" src="https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/77691829/4ef6bcf1-0896-4ed1-ad01-8e0e6c0b2e39">

nav 바 사이 간격도 안맞아요!

2024-01-10 13:47 UTC, Yeonseo-Jo approved these changes
피드백 잘 반영했네요 수고했습니다! 로그인 버튼 위치만 맞추고 머지 하세용

2024-01-10 13:47 UTC, Yeonseo-Jo commented on src/common/constants/NavigationLink.ts
> +  { id: 1, text: '대시보드', path: 'dashboard' },
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ아오

2024-01-10 13:57 UTC, merged