[History] drawer ui & 테마 기능
MOONSHOT-Team/MOONSHOT-CLIENT pull request #72
Opened 2024-01-09 22:44 UTC by Jun-min2

## 🔥 Related Issues

- close #54

## 💜 작업 내용

- [x] 히스토리 drawer ui
- [x] drawer 테마 기능 

## ✅ PR Point

연도에 대해서는 서버로 받는걸로 알고 있어서 일단 스타일만 구현했습니다!

## 😡 Trouble Shooting

useState props 주는 법 + 많은 생각

2024-01-10 01:08 UTC, Yeonseo-Jo requested changes
https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/77691829/8faeb696-2695-4a2a-abeb-514c63db23ae

신ㄱ기한 현상이 발생하는군요 ......
활성화/비활성화/선택 3가지 케이스로 나눠서 다시 구현 plz ..

2024-01-10 01:08 UTC, Yeonseo-Jo commented on src/History/components/HistoryDrawer.tsx
> +          ))}
idx key로 쓰지 말기!

2024-01-10 01:08 UTC, Yeonseo-Jo commented on src/History/components/HistoryDrawer.tsx
> +`;
왜 컨벤션을 안지키니 !!!!!!!!  St 붙여줘 !!!!!!!!1

2024-01-10 01:08 UTC, Yeonseo-Jo commented on src/History/components/HistoryDrawer.tsx
> +        <Year>연도</Year>
<img width="296" alt="image" src="https://github.com/MOONSHOT-Team/MOONSHOT-CLIENT/assets/77691829/f49961dc-ac8e-4bee-af74-52564f898b10">

테마 섹션이랑 연도 섹션 사이 간격이 피그마랑 달라요~

2024-01-10 01:10 UTC, Yeonseo-Jo requested changes

2024-01-10 01:10 UTC, Yeonseo-Jo commented on src/History/components/HistoryDrawer.tsx
> +          <YearButton>2021(1)</YearButton>
여기도 더미데이터 쌓아서 map 돌려서 구현 해놓자!

2024-01-10 01:10 UTC, Yeonseo-Jo commented on src/History/components/ThemeButton.tsx
> +  };
네이밍 컨벤션 지켜라 ~

2024-01-10 01:10 UTC, Yeonseo-Jo commented on src/History/components/ThemeButton.tsx
> +    </ThemeBtn>
여기 로직 다시 생각해봅시다

2024-01-10 01:13 UTC, Yeonseo-Jo commented
아 그리고 뒤에 배경색도 안들어가 있네영 추가 고고

2024-01-10 07:19 UTC, eonseok-jeon requested changes
고생하셨습니다!

피드백 반영해 주세요~

2024-01-10 07:19 UTC, eonseok-jeon commented on src/History/components/HistoryDrawer.tsx
> +  padding: 2.4rem 2.2rem 27.8rem;
아래 쪽 패딩은 안 쓰셔도 되세요
나중에 항목 추가될 지도 모르고,
또 불필요한 여백이 생길 수 있어요

2024-01-10 07:19 UTC, eonseok-jeon commented on src/History/components/HistoryDrawer.tsx
> +  gap: 1.6rem;
```typescript
const Theme = styled.p`
  color: ${({ theme }) => theme.colors.gray_000};
  ${({ theme }) => theme.fonts.body_12_regular};
`;
```
위의 Theme과 동일한 코드니 재사용 하시면 될 거 같습니다

2024-01-10 07:19 UTC, eonseok-jeon commented on src/History/components/HistoryDrawer.tsx
> +  display: flex;
```suggestion
  ${({ theme }) => theme.fonts.body_12_regular};
`;

const YearWrapper = styled.div`
  display: flex;
```

style component 사이에 엔터를 해주면 가독성이 올라갑니다

2024-01-10 07:19 UTC, eonseok-jeon commented on src/History/components/HistoryDrawer.tsx
> +`;
```typescript
const ThemeWrapper = styled.div`
  display: flex;
  flex-wrap: wrap;
  gap: 1.2rem 0.6rem;
`;
```

위와 마찬기지로 YearWrapper와 동일한 코드를 사용하고 계시네요

애초에 테마 부분과 연도 부분이 UI적으로 동일하니까 이 둘에 공통적으로 사용될 컴포넌트를 만들고 이를 재사용하는 식으로 하면 될 거 같습니다

2024-01-10 13:20 UTC, Jun-min2 commented on src/History/components/HistoryDrawer.tsx
> +        <Year>연도</Year>
gap만 보고 padding값을 놓쳤어요 헉스.. 수정하겠습니다!

2024-01-10 20:29 UTC, Yeonseo-Jo requested changes
확인했습니다! 필터링 한개씩만 되도록만 적용 부탁드릴게용

2024-01-10 20:29 UTC, Yeonseo-Jo commented on src/History/components/HistoryDrawer.tsx
> +  /* background-color: ${({ theme }) => theme.colors.gray_650}; */
배경 색 왜 안넣으셨나용?

2024-01-10 20:29 UTC, Yeonseo-Jo commented on src/History/components/HistoryDrawer.tsx
> +          ))}
지금 테마, 연도 모두 `한 번에 하나의 테마 or 연도만 필터링 가능`이라는 요구사항이 기능명세에 명시되어 있어요!
기능 명세서 다시 확인해보고 반영 해주세요 -!

2024-01-10 20:29 UTC, Yeonseo-Jo commented on src/History/components/ThemeButton.tsx
> +    setIsCheckIc(!isCheckIc);
상수와 함수 사이 개행 해주면 좋을것 같습니다!

2024-01-10 20:50 UTC, Jun-min2 commented on src/History/components/HistoryDrawer.tsx
> +  /* background-color: ${({ theme }) => theme.colors.gray_650}; */
버튼 구현하는데.. 배경색이 잘 구분이 안가서... 안보여가지고..

2024-01-14 13:34 UTC, SooY2 approved these changes
굳굳~~ 리뷰 반영도 잘하고~~ 고생해따!!!

2024-01-14 13:34 UTC, SooY2 commented on src/History/index.tsx
> +  const themeData = [{ category: 'GROWTH' }, { category: 'HEALTH' }, { category: 'ECONOMY' }];
서버에서 현재 있는 카테고리값도 따로 빼서 보내주기로 결정했나용??? 명세서 아직 안올라왔길래 궁금해서,,

2024-01-14 13:34 UTC, SooY2 commented on src/History/components/YearButton.tsx
> +const YearBtn = styled.button<{ isActive: boolean }>`
StYearBtn!!

2024-01-14 15:29 UTC, Jun-min2 commented on src/History/index.tsx
> +  const themeData = [{ category: 'GROWTH' }, { category: 'HEALTH' }, { category: 'ECONOMY' }];
준댔어용!

2024-01-15 00:37 UTC, Jun-min2 commented on src/History/index.tsx
> +  const themeData = [{ category: 'GROWTH' }, { category: 'HEALTH' }, { category: 'ECONOMY' }];
민철이한테 받은 데이터 양식으로 drawer도 수정했습니다!

2024-01-15 07:31 UTC, Yeonseo-Jo approved these changes
리뷰 남긴것만 반영후 머지 해주세요!

2024-01-15 07:31 UTC, Yeonseo-Jo commented on src/History/components/HistoryDrawer.tsx
> +  };
여기서는 비교 없이 set만 해줘도 될것 같습니다

2024-01-15 08:16 UTC, Jun-min2 commented on src/History/components/HistoryDrawer.tsx
> +  };
반영 완!

2024-01-15 20:53 UTC, merged